del /S *.toc
del /S *.aux
del /S *.out
del /S *.log
del /S *.synctex.gz
del /S *.synctex
del /S *.pdfsync
del /S *.tmp
del /S *.ps
del /S *.dvi
del /S *.idv
del /S *.4og
del /S *.xref
del /S *.lg
del /S *.4ct
del /S *.4tc
del /S ._.DS_Store
del /S .DS_Store
del /S *.bak
del /S *.tex.bak
